version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"  # Root-Verzeichnis deines Projekts
    schedule:
      interval: "daily"  # Oder "daily", "monthly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 50
